name: Daily Data Processing

on:
  schedule:
    - cron: '0 10 * * *' # Executes at 12:00 (noon) German time (UTC+2 in summer, UTC+1 in winter)
  workflow_dispatch: # Allows manual triggering

jobs:
  run-etl-scripts:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          
      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      - name: Make Directories
        run: |
          cd data
          mkdir hyras 
          ls -lah
        
      - name: Run downloadCurrentYear.py from data/hyras
        run: |
          cd data/hyras
          python ../../etl/downloadCurrentYear.py

      - name: Run createCurrentYear.py from data
        run: |
          cd data
          python ../etl/createCurrentYear.py
          python ../etl/mergeAllCurrentYearJSON.py
          python ../etl/mergeAllPerPlaceCurrentYearJSONpy.py

      - name: Commit and push changes
        env:
          PAT_TOKEN: ${{ secrets.DAILY_PAT }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Daily data update" || echo "No changes to commit"
          git push https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }}.git HEAD:${{ github.ref_name }}
